#pragma once
#include "Visuals.h"
#include <vector>
#include <sal.h>
using std::vector;

constexpr size_t ROOM_WIDTH  = 16;
constexpr size_t ROOM_HEIGHT = 16;

enum class Cardinal
{
    NORTH,
    EAST,
    SOUTH,
    WEST,
};

enum class GridSpaceFlags
{
    GRIDSPACE_EMPTY,
    GRIDSPACE_WALL,
    GRIDSPACE_DOOR,
};

class Room
{
public:
    Room(int x, int y);

    GridSpaceFlags at(_In_range_(0, ROOM_WIDTH - 1) int x, _In_range_(0, ROOM_HEIGHT - 1) int y) const;
    GridSpaceFlags at(Gridspace position) const;

    void GetRoomTexture(TextureGrayscale& tex) const;
    void Generate(); // Generates walls; doors are generated by LevelMap

    int GetX() const;
    int GetY() const;

private:
    GridSpaceFlags& at(_In_range_(0, ROOM_WIDTH - 1) int x, _In_range_(0, ROOM_HEIGHT - 1) int y);
    GridSpaceFlags& at(Gridspace position);
    int mapX, mapY;
    GridSpaceFlags grid[ROOM_WIDTH][ROOM_HEIGHT];
};

class LevelMap
{
public:
    static constexpr size_t PATH_LENGTH = 1;

    size_t NumRooms() const;
    Room& GetRoom(size_t room);
    
    std::pair<size_t, size_t> GetMapSize() const;
    void GetMapTexture(TextureGrayscale& tex) const;
    void Generate(size_t numRooms);

private:
    vector<Room> rooms;
};
